package SpotifyAPITest.UtilityPKG;

public class TokenManager {
    public static String token = "BQBWjIuJpuG61gmJhRC4FBWzITD5Yhw9LTDuyFLCEPlaSA5FcfzlhdzmCuX6QVi6kFcYuISBsr3SnnnDiLOTrasAkkAZDV80ZPRIdiaMYXHZsVBZrmfS-SZlnI5Nzx0N2hF_jbpK2RY4HGGZ-RFPBq63m_HNihDiFypeVMzf7smPR0CGg0KmT7jer1WZQdnrAMWaeABXfNs37OmdOoc0kDxVXGF6FoNSoioe2dTKH_YFBHGocbaFxFyHQEbZrdT1p0giJ1vI1cxlTXfENCIP53i2O19_Pw";
}
